spring:
  redis:
    database: 0
    host: 192.168.1.50
    port: 6379
    password: uqiansoft
    lettuce:
      pool:
        max-active:  10             # 连接池最大连接数（使用负值表示没有限制），由于连接线程安全，所以池不需要很大
        max-idle: 5                 # 连接池中的最大空闲连接
        min-idle: 1                 # 连接池中的最小空闲连接
        max-wait: -1ms              # 获取连接的最大等待时间（使用负值表示没有限制）
    timeout: 10000ms            # redis连接超时时间（使用负值表示没有限制）

# eureka客户端配置
eureka:
  client:
    registry-fetch-interval-seconds: 5              # 向服务中心请求服务注册信息的间隔时间，默认为30秒
    #    register-with-eureka: false                     # 是否向注册中心注册自己，默认true
    service-url:                                    # 服务注册的请求地址
      defaultZone: http://admin:123456@192.168.1.50:8761/eureka/

# feign消费超时配置
ribbon:
  ConnectTimeout: 1000000               # 单位ms
  ReadTimeout: 1000000
  MaxAutoRetries: 0
